
- name: Hello World Sample
  hosts: all
  remote_user: fvivanco
  tasks:
    - name: runnex_launcher
      command: echo "Hola Yorman Yorman"
      command: python3 /home/canvia/Escritorio/borrado.py
